import os, sys, time
from os 
from time import sleep   
os.system("color A")
print("~~" * 50)
print("                                    Anonymous Alon kreker    ")
time.sleep(50)
os.system("cls")
system("clear")
print("~~" * 50)
ip  = input ("Pingaj IP ili Domenu: ")
os.system("ping " + ip)
print("~~" * 50)
time.sleep(50)
os.system("cls")
system("clear")
print("~~" * 50)
port  = input ("Nmap IP: ")
os.system("nmap " + port)
print("~~" * 50)
time.sleep(50)
os.system("cls")
system("clear")
print(+ "~~" * 50)
iph  = input ("IP Host: ")
os.system("host " + iph)
print("~~" * 50)
time.sleep(50)
os.system("cls")
system("clear")

