import os
import time
import sleep
import system
import clear
os.system("color A")
os.system("inxi -c 4")
print("~~" * 50)
print("                                    Anonymous Alon kreker    ")
time.sleep(50)
os.system("cls")
system("clear")
print("~~" * 50)
ip  = input ("Pingaj IP ili Domenu: ")
os.system("ping " + ip)
print("~~" * 50)
time.sleep(50)
os.system("cls")
system("clear")
print("~~" * 50)
port  = input ("Nmap IP: ")
os.system("nmap " + port)
print("~~" * 50)
time.sleep(50)
os.system("cls")
system("clear")
print("~~" * 50)
iph  = input ("IP Host: ")
os.system("host " + iph)
print("~~" * 50)
time.sleep(50)
os.system("cls")
system("clear")
print("~~" * 50)
trcc  = input ("IP Traceroute: ")
os.system("traceroute " + trcc)
print("~~" * 50)
time.sleep(50)
os.system("cls")
system("clear")
print("~~" * 50)
trc  = input ("IP Tracert: ")
os.system("tracert " + trc)
print("~~" * 50)
time.sleep(50)
os.system("cls")
system("clear")
